name: lru-kr
services:
  lru-kr-server:
    image: ghcr.io/devnergis/lru.kr:latest
    container_name: lru-kr-server
    ports:
      - "2001:2001"
    env_file:
      - .env
    networks:
      - lru-kr
    environment:
      TZ: Asia/Seoul
  lru-kr-db:
    image: docker.io/redis/redis-stack-server:latest
    container_name: lru-kr-db
    env_file:
      - .env
    networks:
      - lru-kr
    environment:
      TZ: Asia/Seoul
networks:
  lru-kr:
    driver: bridge
