name: lru-kr
services:
  lru-kr-server:
    image: ghcr.io/devnergis/lru.kr:latest
    container_name: lru-kr-server
    ports:
      - "2001:2001"
    env_file:
      - .env
    networks:
      - lru-kr
    environment:
      TZ: Asia/Seoul
    healthcheck:
      test: curl http://0.0.0.0:2001 || exit 1
    restart: always
  lru-kr-db:
    image: docker.io/redis/redis-stack-server:latest
    container_name: lru-kr-db
    volumes:
      - ${DB_LOCATION}:/data
    env_file:
      - .env
    networks:
      - lru-kr
    environment:
      TZ: Asia/Seoul
      REDIS_ARGS: --requirepass ${DB_PASSWORD}
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
networks:
  lru-kr:
