name: lru-kr
services:
  lru-kr-server:
    image: ghcr.io/devnergis/sqla.re:latest
    container_name: lru-kr-server
    ports:
      - "2001:2001"
    networks:
      - lru-kr
    environment:
      TZ: Asia/Seoul
  lru-kr-db:
    image: redis/redis-stack-server:latest
    container_name: lru-kr-db
    networks:
      - lru-kr
    environment:
      TZ: Asia/Seoul
networks:
  lru-kr:
    driver: bridge
